import type { Metadata } from "next";
import { Lora, Sofia, Silkscreen, Overpass, Limelight } from "next/font/google";
import "./globals.css";

const lora = Lora({
  subsets: ['latin'],
  variable: '--font-lora',
});

const sofia = Sofia({
  subsets: ['latin'],
  weight: ['400'], // Sofia supports limited weights
  variable: '--font-sofia',
});

const silkscreen = Silkscreen({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-silkscreen',
});

const overpass = Overpass({
  subsets: ['latin'],
  weight: ['400','500','600','700','800','900'], // choose available weights
  variable: '--font-overpass',
});

const limelight = Limelight({
  subsets: ['latin'],
  weight:['400'],
  variable: '--font-limelight',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${sofia.variable} ${silkscreen.variable} ${overpass.variable} ${limelight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
